SET @SEASON = 9999;
SET REFERENTIAL_INTEGRITY FALSE;
BEGIN TRANSACTION;

//PERFORMANCE_ID
DELETE FROM PERFORMANCEADVANCE
WHERE PERFORMANCE_ID IN 
 (SELECT ID FROM PERFORMANCE
  WHERE DAY_ID IN 
  (SELECT ID FROM DAY 
    WHERE WEEK_ID IN 
    (SELECT ID FROM WEEK WHERE SEASON_ID = @SEASON)));
    
//PERFORMANCE    
DELETE FROM PERFORMANCE
WHERE 
  DAY_ID IN 
  (SELECT ID FROM DAY 
    WHERE WEEK_ID IN 
    (SELECT ID FROM WEEK WHERE SEASON_ID = @SEASON));

COMMIT;

//EVENT
DELETE FROM EVENT
WHERE 
  DAY_ID IN 
  (SELECT ID FROM DAY 
    WHERE WEEK_ID IN 
    (SELECT ID FROM WEEK WHERE SEASON_ID = @SEASON));
//DAY
DELETE FROM DAY 
  WHERE ID IN 
  (SELECT ID FROM WEEK WHERE SEASON_ID = @SEASON);
//WEEK
DELETE FROM WEEK
  WHERE SEASON_ID = @SEASON;
  
//BUDGET
DELETE FROM BUDGETADJUSTINGENTRY
  WHERE ID IN
  (SELECT ID FROM BUDGETENTRY 
  WHERE ID IN (SELECT ID FROM BUDGET WHERE SEASON_ID = @SEASON));
  
DELETE FROM BUDGETENTRY 
  WHERE ID IN (SELECT ID FROM BUDGET WHERE SEASON_ID = @SEASON);
  
DELETE FROM BUDGET
  WHERE ID IN (SELECT ID FROM BUDGET WHERE SEASON_ID = @SEASON);

//CONTACTS
DELETE FROM SEASONCONTACT
  WHERE ID = @SEASON;

//DEPARTMENTS
DELETE FROM DEPARTMENT
  WHERE SEASON_ID = @SEASON;
  
//SEASON
DELETE FROM SEASON 
  WHERE ID = @SEASON;
  
SET REFERENTIAL_INTEGRITY TRUE;  

